/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Core API
 * Stack application core REST API.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EchoHTTPError,
  ExampleCreateRequest,
  ExampleExampleDTO,
  ExampleRenameRequest
} from '../generated.schemas';

import { coreFetcher } from '../../orval-fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createExampleResponse201 = {
  data: ExampleExampleDTO
  status: 201
}

export type createExampleResponse400 = {
  data: EchoHTTPError
  status: 400
}

export type createExampleResponseSuccess = (createExampleResponse201) & {
  headers: Headers;
};
export type createExampleResponseError = (createExampleResponse400) & {
  headers: Headers;
};

export type createExampleResponse = (createExampleResponseSuccess | createExampleResponseError)

export const getCreateExampleUrl = () => {




  return `/examples`
}

/**
 * @summary Create an example
 */
export const createExample = async (exampleCreateRequest: ExampleCreateRequest, options?: RequestInit): Promise<createExampleResponse> => {

  return coreFetcher<createExampleResponse>(getCreateExampleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exampleCreateRequest)
  }
);}





export const getCreateExampleMutationOptions = <TError = EchoHTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExample>>, TError,{data: ExampleCreateRequest}, TContext>, request?: SecondParameter<typeof coreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof createExample>>, TError,{data: ExampleCreateRequest}, TContext> => {

const mutationKey = ['createExample'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createExample>>, {data: ExampleCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createExample(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateExampleMutationResult = NonNullable<Awaited<ReturnType<typeof createExample>>>
    export type CreateExampleMutationBody = ExampleCreateRequest
    export type CreateExampleMutationError = EchoHTTPError

    /**
 * @summary Create an example
 */
export const useCreateExample = <TError = EchoHTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExample>>, TError,{data: ExampleCreateRequest}, TContext>, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createExample>>,
        TError,
        {data: ExampleCreateRequest},
        TContext
      > => {
      return useMutation(getCreateExampleMutationOptions(options), queryClient);
    }
    export type getExampleResponse200 = {
  data: ExampleExampleDTO
  status: 200
}

export type getExampleResponse404 = {
  data: EchoHTTPError
  status: 404
}

export type getExampleResponseSuccess = (getExampleResponse200) & {
  headers: Headers;
};
export type getExampleResponseError = (getExampleResponse404) & {
  headers: Headers;
};

export type getExampleResponse = (getExampleResponseSuccess | getExampleResponseError)

export const getGetExampleUrl = (id: string,) => {




  return `/examples/${id}`
}

/**
 * @summary Get an example by id
 */
export const getExample = async (id: string, options?: RequestInit): Promise<getExampleResponse> => {

  return coreFetcher<getExampleResponse>(getGetExampleUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExampleQueryKey = (id: string,) => {
    return [
    `/examples/${id}`
    ] as const;
    }


export const getGetExampleQueryOptions = <TData = Awaited<ReturnType<typeof getExample>>, TError = EchoHTTPError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExample>>, TError, TData>>, request?: SecondParameter<typeof coreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExampleQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExample>>> = ({ signal }) => getExample(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExample>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExampleQueryResult = NonNullable<Awaited<ReturnType<typeof getExample>>>
export type GetExampleQueryError = EchoHTTPError


export function useGetExample<TData = Awaited<ReturnType<typeof getExample>>, TError = EchoHTTPError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExample>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExample>>,
          TError,
          Awaited<ReturnType<typeof getExample>>
        > , 'initialData'
      >, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExample<TData = Awaited<ReturnType<typeof getExample>>, TError = EchoHTTPError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExample>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExample>>,
          TError,
          Awaited<ReturnType<typeof getExample>>
        > , 'initialData'
      >, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExample<TData = Awaited<ReturnType<typeof getExample>>, TError = EchoHTTPError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExample>>, TError, TData>>, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an example by id
 */

export function useGetExample<TData = Awaited<ReturnType<typeof getExample>>, TError = EchoHTTPError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExample>>, TError, TData>>, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExampleQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type renameExampleResponse204 = {
  data: void
  status: 204
}

export type renameExampleResponse400 = {
  data: EchoHTTPError
  status: 400
}

export type renameExampleResponse404 = {
  data: EchoHTTPError
  status: 404
}

export type renameExampleResponseSuccess = (renameExampleResponse204) & {
  headers: Headers;
};
export type renameExampleResponseError = (renameExampleResponse400 | renameExampleResponse404) & {
  headers: Headers;
};

export type renameExampleResponse = (renameExampleResponseSuccess | renameExampleResponseError)

export const getRenameExampleUrl = (id: string,) => {




  return `/examples/${id}`
}

/**
 * @summary Rename an example
 */
export const renameExample = async (id: string,
    exampleRenameRequest: ExampleRenameRequest, options?: RequestInit): Promise<renameExampleResponse> => {

  return coreFetcher<renameExampleResponse>(getRenameExampleUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exampleRenameRequest)
  }
);}





export const getRenameExampleMutationOptions = <TError = EchoHTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameExample>>, TError,{id: string;data: ExampleRenameRequest}, TContext>, request?: SecondParameter<typeof coreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof renameExample>>, TError,{id: string;data: ExampleRenameRequest}, TContext> => {

const mutationKey = ['renameExample'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameExample>>, {id: string;data: ExampleRenameRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  renameExample(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RenameExampleMutationResult = NonNullable<Awaited<ReturnType<typeof renameExample>>>
    export type RenameExampleMutationBody = ExampleRenameRequest
    export type RenameExampleMutationError = EchoHTTPError

    /**
 * @summary Rename an example
 */
export const useRenameExample = <TError = EchoHTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameExample>>, TError,{id: string;data: ExampleRenameRequest}, TContext>, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameExample>>,
        TError,
        {id: string;data: ExampleRenameRequest},
        TContext
      > => {
      return useMutation(getRenameExampleMutationOptions(options), queryClient);
    }
