// Shared front library barrel.
//
// The typed React Query client is generated by orval into ./api (one file per
// OpenAPI tag, e.g. api/projects/projects.ts) with types under
// api/generated.schemas. Regenerate with `sklp run generate`.
//
// Import per-tag hooks from the subpath export, e.g.
//   import { useListProjects } from "@tornade/front/api/projects/projects";
//   import type { ProjectProjectDTO } from "@tornade/front/api/generated.schemas";
export { coreFetcher } from "./orval-fetcher";
export * from "./api/generated.schemas";
