apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - namespace.yaml
  - resource-quota.yaml
  - external-secret.yaml
  - redis-pvc.yaml
  - redis.yaml
  - searxng-config.yaml
  - searxng.yaml
  - piper.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: tornade
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: ai
    includeSelectors: false
