apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-quota
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 32Gi
    limits.cpu: "12"
    limits.memory: 96Gi
    persistentvolumeclaims: "12"
