apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tornade-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lalternativefabrique/tornade.git
    targetRevision: main
    path: infra/k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: tornade-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
