/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Core API
 * Stack application core REST API.
 * OpenAPI spec version: 0.1.0
 */

export interface ExampleRenameRequest {
  name?: string;
}
