apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tornade-prod

resources:
  - namespace.yaml
  - tornade.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: tornade
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
